#!/bin/bash 
tmpfile=$$.fifo #创建管道名称 
mkfifo $tmpfile #创建管道 
exec 4<>$tmpfile #创建文件标示4，以读写方式操作管道$tmpfile 
rm $tmpfile   #将创建的管道文件清除 
                                                                                 
thred=4 #指定并发个数 
seq=(1 2 3 4 5 6 7 8 9 21 22 23 24 25 31 32 33 34 35) #创建任务列表 
                                                                                 
# 为并发线程创建相应个数的占位 
{ 
for (( i = 1;i<=${thred};i++ )) 
do 
echo; #因为read命令一次读取一行，一个echo默认输出一个换行符，所以为每个线程输出一个占位换行 
done 
} >&4 #将占位信息写入管道 
                                                                                 
for id in ${seq} #从任务列表 seq 中按次序获取每一个任务 
do 
  read #读取一行，即fd4中的一个占位符 
  (./ur_command ${id};echo >&4 ) & #在后台执行任务ur_command 并将任务 ${id} 赋给当前任务；任务执行完后在fd4种写入一个占位符 
done <&4 #指定fd4为整个for的标准输入 
wait  #等待所有在此shell脚本中启动的后台任务完成 
exec 4>&- #关闭管道 
